[pytest]
addopts =
    --browser=chromium
    -v
    -s
    --headed
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure
    --alluredir=report/allure_result
    --base-url=https://automationexercise.com/

markers =
    ui: ui automation
    smoke: smoke tests
    api: api testing
    e2e: end to end testing